  name: "Create Stable Candidate"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  create_stable_candidate:
    runs-on:  ubuntu-latest
    steps:
      - name: "GetTime"
        id: get_time
        runs: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB.OUTPUTS
      - name: "Checkout"      
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Create Stable Candidate Branch"
        runs: |
          git checkout -b stable-candidate-${{ steps.get_time.outputs.today }}
          git push --set-upstream origin stable-candidate-${{ steps.get_time.outputs.today }}
        
