name: "Set Stable Tag"

on:
  workflow_dispatch:
    inputs:
      candidate_branch:
          description: 'Candidate Branch Name'
          required: true
          type: string
  
permissions:
  contents: write

jobs:

  create_stable_candidate:
    runs-on:  ubuntu-latest
    steps:     
      - name: "Checkout"      
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.candidate_branch }}     
      - name: "Checkout commit and apply tag"
        run: |
          git config --global user.email "github@github.com"
          git config --global user.name "GitHub Action Bot"
          git tag -fa stable -m “stable”
          git push --tags --force

        
